// PRIMARY COLORS
export const SPRING_PRIMARY_COLOR = '#59CC8E';
export const SUMMER_PRIMARY_COLOR = '#fdb74d';
export const AUTUMN_PRIMARY_COLOR = '#D7904F';
export const WINTER_PRIMARY_COLOR = '#5B5B5B';

// PRIMARY DARK COLORS
export const SPRING_PRIMARY_DARK_COLOR = '#e79d2c';
export const SUMMER_PRIMARY_DARK_COLOR = '#13BB61';
export const AUTUMN_PRIMARY_DARK_COLOR = '#BB6413';
export const WINTER_PRIMARY_DARK_COLOR = '#2F2D2B';
